### ISSUE TITLE
timerep fails to build with time-1.11

### ISSUE THREAD

**Issue by juhp** [HugoDaniel/timerep#19]
```shellsession
$ stack --resolver nightly build timerep
timerep> stack-83dd043523002f44/timerep-2.0.1.0/Data/Time/RFC2822.hs:74:24: error:
timerep>     • Variable not in scope:
timerep>         parseTime :: TimeLocale -> String -> String -> Maybe ZonedTime
timerep>     • Perhaps you meant ‘parseTimeM’ (imported from Data.Time.Format)
timerep>    |
timerep> 74 |         parse format = parseTime defaultTimeLocale (toString' format) t'
timerep>    |                        ^^^^^^^^^
```

**Comment by k0ral** [comment]
Fixed in [release `2.1.0.0`](https://hackage.haskell.org/package/timerep-2.1.0.0).

Thank you for reporting :) .
